name: Deploy Application
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t my-app:latest .
      - name: Push to Docker Hub
        run: |
          docker tag my-app:latest my-dockerhub-user/my-app:latest
          docker push my-dockerhub-user/my-app:latest
      - name: Apply Kubernetes Deployment
        run: kubectl apply -f k8s/
