# Pipeline para Lambda
name: Deploy Lambda Function

on:
  push:
    branches:
      - main # é a unica que tem, mas provavelmente será outra

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Prepare deployment package
        run: zip -r deployment-package.zip .

      - name: Debug
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        run: |
          FUNCTION_NAME="postech-lambda-function"
          echo "Testing if function exists..."
          aws lambda get-function --function-name $FUNCTION_NAME --region "us-east-1" || echo "Function not found"
          echo "Exiting script for debug."
          exit 0

      - name: Deploy or Update AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          FUNCTION_NAME="postech-lambda-function"
          REGION="us-east-1"
          ZIP_FILE="deployment-package.zip"
          ROLE_ARN="arn:aws:iam::180294201352:user/github-actions-lambda"
          HANDLER="findByCPF.handler"
          RUNTIME="nodejs18.x"

          echo "Checking if function exists..."
          if aws lambda get-function --function-name $FUNCTION_NAME --region $REGION > /dev/null 2>&1; then
            echo "Function exists. Updating the code..."
            aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --zip-file fileb://$ZIP_FILE
          else
            echo "Function does not exist. Creating the function..."
            aws lambda create-function \
              --function-name $FUNCTION_NAME \
              --region $REGION \
              --runtime $RUNTIME \
              --role $ROLE_ARN \
              --handler $HANDLER \
              --zip-file fileb://$ZIP_FILE
          fi
