# Pipeline para Lambda
name: Deploy Lambda Function

on:
  push:
    branches:
      - main # é a unica que tem, mas provavelmente será outra

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: npm install

      - name: Run tests
        uses: npm test

        # configurando credenciais AWS
      - name: Deploy to AWS Lambda
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

        # upload para AWS Lambda
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name lambda-function \
            --zip-file fileb://deployment-package.zip
