# workflow da Terraform nos k8s
name: Apply Kubernetes Infrastructure
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform init and apply
        run: |
          terraform init
          terraform apply -auto-approve
